import { Injectable } from '@angular/core';


@Injectable()
export class UrlMasterProvider {

static urlAPI:String="https://mountdreams.id/mis/";
static token1:String="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55Q29kZSI6IjAxIiwibGFzdFBhc3NDaGFuZ2UiOiIyMDE3LTA4LTAxIDAwOjAwOjAwLjAiLCJjb21wYW55X2lkIjoyMiwiaXBBZGRyZXNzIjoiMDowOjA6MDowOjA6MDoxIiwiaXNzIjoiaHR0cHM6Ly9tb3VudGRyZWFtcy5pZCIsImVtcGxveWVlSWQiOjI5MiwiZm90byI6IiIsInVzZXJfaWQiOjI5LCJjb21wYW55IjoiUFQuIE1vdW50IERyZWFtcyBJbmRvbmVzaWEgMSIsImZ1bGxuYW1lIjoiSW5kcmEgU3VyeWF3YW4iLCJleHAiOjE1MDU4NzA0Mzc1ODIsImlhdCI6MTUwNTY5NzYzNzU4MiwidXNlcm5hbWUiOiJpbmRyYSJ9.vbJgJhOlgji2Y-i5n9SnThSoVy4l_dQLwKYxV0io5xE";
static token2:String="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55Q29kZSI6IjAxIiwibGFzdFBhc3NDaGFuZ2UiOiIyMDE3LTA4LTAxIDAwOjAwOjAwLjAiLCJjb21wYW55X2lkIjoyMiwiaXBBZGRyZXNzIjoiMDowOjA6MDowOjA6MDoxIiwiaXNzIjoiaHR0cHM6Ly9tb3VudGRyZWFtcy5pZCIsImVtcGxveWVlSWQiOjMzMSwiZm90byI6bnVsbCwidXNlcl9pZCI6NzksImNvbXBhbnkiOiJQVC4gTW91bnQgRHJlYW1zIEluZG9uZXNpYSAxIiwiZnVsbG5hbWUiOiJIZW5kcmEgRWZlbmRpIiwiZXhwIjoxNTA1ODcwNzQ5Nzk4LCJpYXQiOjE1MDU2OTc5NDk3OTgsInVzZXJuYW1lIjoiaGVuZHJhIn0.RQfnhIof6hAh_L184PvEi1mGxBpE3aZkdiRO9TEgURM";
}
